package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class AttributeGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeGroupAllPropertiesEquals(AttributeGroup expected, AttributeGroup actual) {
        assertAttributeGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertAttributeGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeGroupAllUpdatablePropertiesEquals(AttributeGroup expected, AttributeGroup actual) {
        assertAttributeGroupUpdatableFieldsEquals(expected, actual);
        assertAttributeGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeGroupAutoGeneratedPropertiesEquals(AttributeGroup expected, AttributeGroup actual) {
        assertThat(expected)
            .as("Verify AttributeGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeGroupUpdatableFieldsEquals(AttributeGroup expected, AttributeGroup actual) {
        assertThat(expected)
            .as("Verify AttributeGroup relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e ->
                assertThat(e.getCreatedDate())
                    .as("check createdDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedDate())
            )
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e ->
                assertThat(e.getLastModifiedDate())
                    .as("check lastModifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getLastModifiedDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttributeGroupUpdatableRelationshipsEquals(AttributeGroup expected, AttributeGroup actual) {
        assertThat(expected)
            .as("Verify AttributeGroup relationships")
            .satisfies(e ->
                assertThat(e.getCustomConfiguration()).as("check customConfiguration").isEqualTo(actual.getCustomConfiguration())
            );
    }
}
